### ISSUE TITLE
How can I make DocZ more printer friendly?

### ISSUE THREAD

**Issue by RayBans2111** [pedronauck/docz#1623]
## How can I make my DocZ project printer friendly?

**Description**
Hello, I recently started a small project using DocZ as the framework. I wanted to know if there is a way to achieve a nicer layout of my DocZ project when I go to print it (ctrl + p). Right now, the navigation bar on the side and top header bar appear in the print preview, but it would be nice to remove those and simply print off the content inside the main view of the DocZ site. 

Can this be done? I tried searching around in the documentation, but I had no luck. Thanks in advance!

**Comment by Cavitt** [comment]
Should be easy to override any styling with a print media query

```css
@media print { 
  /* All your print styles go here */
  #header, #footer, #nav { display: none !important; } 
}
```
